// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/libros": {
    params: {};
  };
  "/autores": {
    params: {};
  };
  "/autores/:authorId": {
    params: {
      "authorId": string;
    };
  };
  "/generosTodos": {
    params: {};
  };
  "/generosTodos/:slug": {
    params: {
      "slug": string;
    };
  };
  "/detalle/:bookId": {
    params: {
      "bookId": string;
    };
  };
  "/users": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/:bookId/resena": {
    params: {
      "bookId": string;
    };
  };
  "/biblioteca": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/admin/login": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/admin/users": {
    params: {};
  };
  "/admin/books": {
    params: {};
  };
  "/admin/authors": {
    params: {};
  };
  "/admin/books/new": {
    params: {};
  };
  "/admin/authors/new": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/libros" | "/autores" | "/autores/:authorId" | "/generosTodos" | "/generosTodos/:slug" | "/detalle/:bookId" | "/users" | "/contact" | "/login" | "/register" | "/:bookId/resena" | "/biblioteca" | "/profile" | "/admin/login" | "/admin" | "/admin/users" | "/admin/books" | "/admin/authors" | "/admin/books/new" | "/admin/authors/new";
  };
  "routes/_index.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/_libros.jsx": {
    id: "routes/_libros";
    page: "/libros";
  };
  "routes/_autores.jsx": {
    id: "routes/_autores";
    page: "/autores";
  };
  "routes/autor.$authorId.jsx": {
    id: "routes/autor.$authorId";
    page: "/autores/:authorId";
  };
  "routes/_generosTodos.jsx": {
    id: "routes/_generosTodos";
    page: "/generosTodos";
  };
  "routes/genero.$slug.jsx": {
    id: "routes/genero.$slug";
    page: "/generosTodos/:slug";
  };
  "routes/detalle.$bookId.jsx": {
    id: "routes/detalle.$bookId";
    page: "/detalle/:bookId";
  };
  "routes/users.jsx": {
    id: "routes/users";
    page: "/users";
  };
  "routes/contact.jsx": {
    id: "routes/contact";
    page: "/contact";
  };
  "routes/login.jsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/register.jsx": {
    id: "routes/register";
    page: "/register";
  };
  "routes/$bookId.resena.jsx": {
    id: "routes/$bookId.resena";
    page: "/:bookId/resena";
  };
  "routes/_bibliotecaUsuario.jsx": {
    id: "routes/_bibliotecaUsuario";
    page: "/biblioteca";
  };
  "routes/user-profile.jsx": {
    id: "routes/user-profile";
    page: "/profile";
  };
  "routes/admin-login.jsx": {
    id: "routes/admin-login";
    page: "/admin/login";
  };
  "routes/admin-dashboard.jsx": {
    id: "routes/admin-dashboard";
    page: "/admin";
  };
  "routes/admin-users.jsx": {
    id: "routes/admin-users";
    page: "/admin/users";
  };
  "routes/admin-books.jsx": {
    id: "routes/admin-books";
    page: "/admin/books";
  };
  "routes/admin-authors.jsx": {
    id: "routes/admin-authors";
    page: "/admin/authors";
  };
  "routes/admin-new-book.jsx": {
    id: "routes/admin-new-book";
    page: "/admin/books/new";
  };
  "routes/admin-new-author.jsx": {
    id: "routes/admin-new-author";
    page: "/admin/authors/new";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/_index": typeof import("./app/routes/_index.jsx");
  "routes/_libros": typeof import("./app/routes/_libros.jsx");
  "routes/_autores": typeof import("./app/routes/_autores.jsx");
  "routes/autor.$authorId": typeof import("./app/routes/autor.$authorId.jsx");
  "routes/_generosTodos": typeof import("./app/routes/_generosTodos.jsx");
  "routes/genero.$slug": typeof import("./app/routes/genero.$slug.jsx");
  "routes/detalle.$bookId": typeof import("./app/routes/detalle.$bookId.jsx");
  "routes/users": typeof import("./app/routes/users.jsx");
  "routes/contact": typeof import("./app/routes/contact.jsx");
  "routes/login": typeof import("./app/routes/login.jsx");
  "routes/register": typeof import("./app/routes/register.jsx");
  "routes/$bookId.resena": typeof import("./app/routes/$bookId.resena.jsx");
  "routes/_bibliotecaUsuario": typeof import("./app/routes/_bibliotecaUsuario.jsx");
  "routes/user-profile": typeof import("./app/routes/user-profile.jsx");
  "routes/admin-login": typeof import("./app/routes/admin-login.jsx");
  "routes/admin-dashboard": typeof import("./app/routes/admin-dashboard.jsx");
  "routes/admin-users": typeof import("./app/routes/admin-users.jsx");
  "routes/admin-books": typeof import("./app/routes/admin-books.jsx");
  "routes/admin-authors": typeof import("./app/routes/admin-authors.jsx");
  "routes/admin-new-book": typeof import("./app/routes/admin-new-book.jsx");
  "routes/admin-new-author": typeof import("./app/routes/admin-new-author.jsx");
};