// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/genre": {
    params: {};
  };
  "/users": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/genre" | "/users" | "/login" | "/register";
  };
  "routes/_index.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/_genre.jsx": {
    id: "routes/_genre";
    page: "/genre";
  };
  "routes/users.jsx": {
    id: "routes/users";
    page: "/users";
  };
  "routes/login.jsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/register.jsx": {
    id: "routes/register";
    page: "/register";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/_index": typeof import("./app/routes/_index.jsx");
  "routes/_genre": typeof import("./app/routes/_genre.jsx");
  "routes/users": typeof import("./app/routes/users.jsx");
  "routes/login": typeof import("./app/routes/login.jsx");
  "routes/register": typeof import("./app/routes/register.jsx");
};